---
name: Run tests

on: [push, pull_request, workflow_dispatch]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Clone code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install build dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Fetch latest packages data and build the website
        run: |
          make generate

      - name: Check files against the pre-commit config
        run: |
          pre-commit run --all-files --show-diff-on-failure
